# Configuración de ShareIsCare
# Nota: Cambiar las credenciales por defecto por seguridad
port: 8080
root_dir: .
title: ShareIsCare
username: admin
password: shareiscare
secret_key: "1743889330156877000"
