# ShareIsCare Configuration
# Note: Change default credentials for security
port: 8080
root_dir: .
title: ShareIsCare
username: admin
password: shareiscare
secret_key: "1743889330156877000"
hostname: jg6vsfxu.shareiscare.com
