name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          check-latest: true

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Generate templ code
        run: templ generate

      - name: Run tests
        run: go test -v -short ./...

      - name: Verify cross-compilation for Raspberry Pi
        run: |
          echo "Verificando compilación para Raspberry Pi..."
          if GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=0 go build -o /tmp/shareiscare-arm-test main.go; then
            echo "✓ La compilación para Raspberry Pi es correcta"
            rm /tmp/shareiscare-arm-test
          else
            echo "✗ Error en la compilación para Raspberry Pi"
            exit 1