name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          check-latest: true

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Generate templ code
        run: templ generate

      - name: Run tests
        run: go test -v -short ./...

      # Verificación de Raspberry Pi en pasos separados para evitar problemas de sintaxis
      - name: Compile for Raspberry Pi
        run: GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=0 go build -o /tmp/shareiscare-arm-test main.go

      - name: Clean up
        if: success()
        run: rm -f /tmp/shareiscare-arm-test && echo "✓ La compilación para Raspberry Pi es correcta"